[package]
name = "slopjson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.18"
gio = "0.18"
glib = "0.18"
serde_json = "1.0"
serde_yaml = "0.9"
parquet = "55"
arrow = "55"
bytes = "1.7"
